version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181"
    hostname: zookeeper
  kafka:
    image: wurstmeister/kafka
    command: [start-kafka.sh]
    ports:
      - "9092:9092"
    hostname: kafka
    environment:
      KAFKA_CREATE_TOPICS: "MyTopic:1:1" # topic:partition:replicas
      KAFKA_ADVERTISED_HOST_NAME: kafka # docker-machine ip
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - "zookeeper"
  consumer:
    image: consumer
    hostname: consumer
    environment:
        APP_NAME: "consumer"
        KAFKA_HOSTNAME: "kafka"
        TOPICS: "MyTopic"
    depends_on:
      - "zookeeper"
      - "kafka"
      - "producer"
  producer:
    image: producer
    hostname: producer
    environment:
        APP_NAME: "producer"
        KAFKA_HOSTNAME: "kafka"
        TOPICS: "MyTopic"
    depends_on:
      - "zookeeper"
      - "kafka"

